import { ok } from "@/lib/api-response";

export const dynamic = "force-dynamic";

// GET /api/google-api-mapping — complete Google Business Profile API → DB mapping (doc 20)
export async function GET() {
  return ok({
    googleApis: [
      { name: "OAuth 2.0", purpose: "Authentication", status: "configured" },
      { name: "Business Profile API", purpose: "Profile management, reviews, posts", status: "configured" },
      { name: "Business Information API", purpose: "Business info, categories, hours, services", status: "configured" },
      { name: "Business Performance API", purpose: "Analytics metrics (search/views/calls)", status: "configured" },
      { name: "Google People API", purpose: "User profile info", status: "available" },
      { name: "Google OAuth API", purpose: "Token refresh & validation", status: "configured" },
    ],
    authFlow: [
      { step: 1, action: "User Login", detail: "MyFNG SSO credentials" },
      { step: 2, action: "Google OAuth", detail: "Redirect to Google consent screen" },
      { step: 3, action: "Authorization Code", detail: "Google returns auth code to callback" },
      { step: 4, action: "Access Token", detail: "Backend exchanges code for access token" },
      { step: 5, action: "Refresh Token", detail: "Stored encrypted for auto-refresh" },
      { step: 6, action: "Encrypted Database", detail: "Tokens stored in google_accounts table" },
      { step: 7, action: "API Calls", detail: "Backend uses access token for all Google API calls" },
    ],
    mappings: [
      {
        id: "google_account",
        googleObject: "Google Account",
        dbTable: "google_accounts",
        dbModel: "GoogleAccount",
        fields: [
          { google: "Google Email", db: "email", type: "TEXT", notes: "OAuth account email" },
          { google: "Google User ID", db: "googleUserId", type: "TEXT", notes: "Unique Google user identifier" },
          { google: "Refresh Token", db: "refreshToken", type: "TEXT", notes: "Encrypted at rest" },
          { google: "Access Token", db: "accessToken", type: "TEXT", notes: "Encrypted, auto-refreshed" },
          { google: "Expiry", db: "tokenExpiry", type: "TIMESTAMP", notes: "Auto-refresh before expiry" },
          { google: "Scopes", db: "scopesJson", type: "JSON", notes: "Granted OAuth scopes" },
        ],
        syncDirection: "google-to-db",
        status: "active",
      },
      {
        id: "business_profile",
        googleObject: "Business Profile",
        dbTable: "google_business_profiles",
        dbModel: "GoogleBusinessProfile",
        fields: [
          { google: "Google Location ID", db: "googleLocationId", type: "TEXT (UNIQUE)", notes: "Primary external identifier" },
          { google: "Business Name", db: "profileName", type: "TEXT", notes: "" },
          { google: "Verification Status", db: "verificationState", type: "TEXT", notes: "verified | unverified | pending" },
          { google: "Average Rating", db: "averageRating", type: "FLOAT", notes: "0-5 scale" },
          { google: "Review Count", db: "totalReviews", type: "INT", notes: "" },
          { google: "Primary Category", db: "primaryCategory", type: "TEXT", notes: "" },
          { google: "Additional Categories", db: "additionalCategoriesJson", type: "JSON", notes: "Array of category names" },
          { google: "Profile Status", db: "profileStatus", type: "TEXT", notes: "active | suspended | disabled" },
          { google: "Map URL", db: "mapUrl", type: "TEXT", notes: "Google Maps link" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "30 minutes",
        status: "active",
      },
      {
        id: "business_information",
        googleObject: "Business Information",
        dbTable: "business_information",
        dbModel: "BusinessInformation",
        fields: [
          { google: "Description", db: "description", type: "TEXT", notes: "Business description" },
          { google: "Website", db: "website", type: "TEXT", notes: "" },
          { google: "Phone", db: "phone", type: "TEXT", notes: "Also on Location table" },
          { google: "Appointment URL", db: "appointmentUrl", type: "TEXT", notes: "" },
          { google: "Opening Hours", db: "openingHoursJson", type: "JSON", notes: "Legacy JSON; BusinessHour table is canonical" },
          { google: "Special Hours", db: "specialHoursJson", type: "JSON", notes: "Holiday hours" },
          { google: "Services", db: "servicesJson", type: "JSON", notes: "" },
          { google: "Attributes", db: "attributesJson", type: "JSON", notes: "" },
        ],
        syncDirection: "bidirectional",
        syncFrequency: "30 minutes",
        status: "active",
      },
      {
        id: "business_hours",
        googleObject: "Business Hours",
        dbTable: "business_hours",
        dbModel: "BusinessHour",
        fields: [
          { google: "Day of Week", db: "dayOfWeek", type: "INT", notes: "0=Sun, 6=Sat" },
          { google: "Opening Time", db: "openTime", type: "TEXT", notes: "HH:MM format" },
          { google: "Closing Time", db: "closeTime", type: "TEXT", notes: "HH:MM format" },
          { google: "Is Closed", db: "isClosed", type: "BOOLEAN", notes: "true = closed all day" },
        ],
        syncDirection: "bidirectional",
        syncFrequency: "30 minutes",
        status: "active",
      },
      {
        id: "special_hours",
        googleObject: "Holiday Hours",
        dbTable: "special_hours",
        dbModel: "SpecialHour",
        fields: [
          { google: "Date", db: "date", type: "DATE", notes: "Holiday date" },
          { google: "Opening Time", db: "openTime", type: "TEXT", notes: "Null if closed" },
          { google: "Closing Time", db: "closeTime", type: "TEXT", notes: "Null if closed" },
          { google: "Is Closed", db: "isClosed", type: "BOOLEAN", notes: "true = closed on this date" },
        ],
        syncDirection: "bidirectional",
        syncFrequency: "daily",
        status: "active",
      },
      {
        id: "categories",
        googleObject: "Categories",
        dbTable: "business_categories",
        dbModel: "BusinessCategory",
        fields: [
          { google: "Primary Category", db: "categoryName (isPrimary=true)", type: "TEXT", notes: "One primary per location" },
          { google: "Additional Categories", db: "categoryName (isPrimary=false)", type: "TEXT", notes: "Multiple rows" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "daily",
        status: "active",
      },
      {
        id: "services",
        googleObject: "Services",
        dbTable: "services",
        dbModel: "Service",
        fields: [
          { google: "Service Name", db: "serviceName", type: "TEXT", notes: "" },
          { google: "Description", db: "description", type: "TEXT", notes: "" },
          { google: "Category", db: "category", type: "TEXT", notes: "" },
          { google: "Status", db: "status", type: "TEXT", notes: "active | inactive" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "daily",
        status: "active",
      },
      {
        id: "products",
        googleObject: "Products",
        dbTable: "products",
        dbModel: "Product",
        fields: [
          { google: "Product Name", db: "productName", type: "TEXT", notes: "" },
          { google: "Description", db: "description", type: "TEXT", notes: "" },
          { google: "Price", db: "price", type: "FLOAT", notes: "In INR" },
          { google: "Category", db: "category", type: "TEXT", notes: "" },
          { google: "Image URL", db: "imageUrl", type: "TEXT", notes: "" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "future",
        status: "future-ready",
      },
      {
        id: "photos",
        googleObject: "Photos",
        dbTable: "business_photos",
        dbModel: "BusinessPhoto",
        fields: [
          { google: "Google Photo ID", db: "googlePhotoId", type: "TEXT", notes: "Unique Google identifier" },
          { google: "Image URL", db: "imageUrl", type: "TEXT", notes: "Stored/cached URL" },
          { google: "Thumbnail URL", db: "thumbnailUrl", type: "TEXT", notes: "Compressed preview" },
          { google: "Source", db: "source", type: "TEXT", notes: "manual | google | ai" },
          { google: "Status", db: "status", type: "TEXT", notes: "active | deleted" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "daily",
        status: "active",
      },
      {
        id: "reviews",
        googleObject: "Reviews",
        dbTable: "reviews",
        dbModel: "Review",
        fields: [
          { google: "Review ID", db: "googleReviewId", type: "TEXT (UNIQUE)", notes: "No duplicates allowed" },
          { google: "Reviewer Name", db: "authorName", type: "TEXT", notes: "" },
          { google: "Reviewer Photo", db: "authorPhoto", type: "TEXT", notes: "Profile image URL" },
          { google: "Rating", db: "rating", type: "INT", notes: "1-5" },
          { google: "Review Text", db: "text", type: "TEXT", notes: "" },
          { google: "Language", db: "reviewLanguage", type: "TEXT", notes: "en, hi, mr, etc." },
          { google: "Review Time", db: "createdAt", type: "TIMESTAMP", notes: "When review was posted" },
          { google: "Update Time", db: "updatedAt", type: "TIMESTAMP", notes: "Last modification" },
          { google: "Sentiment", db: "sentiment", type: "TEXT", notes: "AI-generated: positive | neutral | negative" },
          { google: "Reply Status", db: "replyStatus", type: "TEXT", notes: "pending | replied | ignored" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "5 minutes",
        status: "active",
      },
      {
        id: "review_replies",
        googleObject: "Review Replies",
        dbTable: "review_replies",
        dbModel: "ReviewReply",
        fields: [
          { google: "Reply Text", db: "replyText", type: "TEXT", notes: "Published reply content" },
          { google: "Reply Source", db: "replySource", type: "TEXT", notes: "manual | ai | template" },
          { google: "Reply Time", db: "googleReplyTime", type: "TIMESTAMP", notes: "When Google confirmed" },
          { google: "Status", db: "status", type: "TEXT", notes: "draft | approved | published | failed" },
          { google: "Approved By", db: "approvedBy", type: "UUID", notes: "User who approved" },
          { google: "Published By", db: "publishedBy", type: "UUID", notes: "User who published" },
        ],
        syncDirection: "db-to-google",
        syncFrequency: "on-demand",
        status: "active",
      },
      {
        id: "google_posts",
        googleObject: "Google Posts",
        dbTable: "google_posts (posts)",
        dbModel: "Post",
        fields: [
          { google: "Google Post ID", db: "googlePostId", type: "TEXT", notes: "Returned after publish" },
          { google: "Title", db: "title", type: "TEXT", notes: "Max 60 chars" },
          { google: "Description", db: "content", type: "TEXT", notes: "100-180 words suggested" },
          { google: "Post Type", db: "type", type: "TEXT", notes: "whats_new | offer | event | update" },
          { google: "CTA Type", db: "ctaType", type: "TEXT", notes: "book | call | learn_more | order | sign_up" },
          { google: "CTA URL", db: "ctaUrl", type: "TEXT", notes: "Landing page URL" },
          { google: "Image URL", db: "imageUrl", type: "TEXT", notes: "Optional" },
          { google: "Status", db: "status", type: "TEXT", notes: "draft | scheduled | published | failed" },
          { google: "Publish Time", db: "publishedAt", type: "TIMESTAMP", notes: "When published to Google" },
          { google: "Schedule Time", db: "scheduledAt", type: "TIMESTAMP", notes: "Future publish time" },
        ],
        syncDirection: "db-to-google",
        syncFrequency: "on-demand",
        status: "active",
      },
      {
        id: "analytics_daily",
        googleObject: "Performance Metrics",
        dbTable: "analytics_daily",
        dbModel: "AnalyticDaily",
        fields: [
          { google: "Search Views", db: "searchViews", type: "INT", notes: "Google search impressions" },
          { google: "Maps Views", db: "mapsViews", type: "INT", notes: "Google Maps impressions" },
          { google: "Website Clicks", db: "websiteClicks", type: "INT", notes: "Clicks to website" },
          { google: "Phone Calls", db: "phoneCalls", type: "INT", notes: "Call button clicks" },
          { google: "Direction Requests", db: "directionRequests", type: "INT", notes: "Driving direction requests" },
          { google: "Bookings", db: "bookings", type: "INT", notes: "Appointment bookings" },
        ],
        syncDirection: "google-to-db",
        syncFrequency: "daily (2 AM)",
        status: "active",
      },
    ],
    aggregationFlow: [
      { stage: "Daily", source: "Google Performance API", target: "analytics_daily", detail: "Raw daily metrics per location" },
      { stage: "Monthly", source: "analytics_daily", target: "analytics_monthly", detail: "Aggregated monthly totals + avg rating" },
      { stage: "Dashboard", source: "analytics_daily + analytics_monthly", target: "dashboard_cache", detail: "Precomputed KPI widgets" },
    ],
    syncDirection: {
      googleToDb: ["Profile data", "Reviews", "Analytics", "Photos", "Categories", "Services", "Business hours"],
      dbToGoogle: ["Review replies", "Google posts", "Business info updates", "Hours updates", "Photo uploads"],
    },
    syncFrequencies: [
      { entity: "Reviews", frequency: "Every 5 minutes", queue: "review-sync", priority: "high" },
      { entity: "Business Information", frequency: "Every 30 minutes", queue: "google-sync", priority: "high" },
      { entity: "Business Hours", frequency: "Every 30 minutes", queue: "google-sync", priority: "medium" },
      { entity: "Posts Status", frequency: "Every 30 minutes", queue: "post-sync", priority: "medium" },
      { entity: "Photos", frequency: "Daily", queue: "google-sync", priority: "low" },
      { entity: "Analytics", frequency: "Daily (2 AM)", queue: "analytics-sync", priority: "high" },
      { entity: "Categories", frequency: "Daily", queue: "google-sync", priority: "low" },
      { entity: "Services", frequency: "Daily", queue: "google-sync", priority: "low" },
      { entity: "Products", frequency: "Future", queue: "—", priority: "future" },
    ],
    errorMapping: [
      { httpCode: 401, meaning: "Unauthorized — token expired or invalid", action: "Refresh token, retry once", retryable: false, logLevel: "warning" },
      { httpCode: 403, meaning: "Forbidden — insufficient permissions", action: "Log, notify admin, do not retry", retryable: false, logLevel: "error" },
      { httpCode: 404, meaning: "Not Found — resource deleted on Google", action: "Archive local record, log", retryable: false, logLevel: "info" },
      { httpCode: 429, meaning: "Too Many Requests — rate limit exceeded", action: "Exponential backoff, retry", retryable: true, logLevel: "warning" },
      { httpCode: 500, meaning: "Internal Server Error — Google side", action: "Retry with backoff", retryable: true, logLevel: "error" },
      { httpCode: 503, meaning: "Service Unavailable — temporary", action: "Retry with backoff", retryable: true, logLevel: "warning" },
    ],
    retryPolicy: {
      retry: [
        { condition: "Network Failure", backoff: "30s → 2min → 10min", maxRetries: 3 },
        { condition: "Timeout (>30s)", backoff: "30s → 2min → 10min", maxRetries: 3 },
        { condition: "429 Rate Limit", backoff: "Exponential: 1s → 2s → 4s → 8s → 16s", maxRetries: 5 },
        { condition: "500/503 Temporary Server Error", backoff: "30s → 2min → 10min", maxRetries: 3 },
      ],
      doNotRetry: [
        { condition: "401 Unauthorized", reason: "Need OAuth re-authorization, not a retry issue" },
        { condition: "403 Forbidden", reason: "Permission/scoping issue, retrying won't help" },
        { condition: "Validation Errors (400)", reason: "Bad request payload, need code fix" },
        { condition: "404 Not Found", reason: "Resource doesn't exist on Google" },
      ],
    },
    rateLimiting: {
      strategy: ["Request Queue", "Batch Processing", "Exponential Backoff", "Retry with Jitter"],
      googleLimits: { readApi: "2000 reads/min", writeApi: "150 writes/min", quotaPerDay: "Depends on project" },
      implementation: "All Google API calls go through backend queue workers. Frontend never calls Google directly.",
    },
    serviceLayer: [
      { service: "GoogleOAuthService", responsibility: "OAuth flow, token refresh, token encryption", methods: ["getAuthUrl()", "exchangeCode()", "refreshToken()", "revokeToken()"] },
      { service: "GoogleProfileService", responsibility: "Import & sync business profiles", methods: ["listAccounts()", "listLocations()", "getProfile()", "syncProfile()"] },
      { service: "GoogleReviewService", responsibility: "Fetch & sync reviews", methods: ["listReviews()", "getReview()", "syncReviews()"] },
      { service: "GoogleReplyService", responsibility: "Publish review replies", methods: ["publishReply()", "deleteReply()"] },
      { service: "GooglePostService", responsibility: "Create, publish, delete Google posts", methods: ["createPost()", "publishPost()", "deletePost()", "listPosts()"] },
      { service: "GoogleAnalyticsService", responsibility: "Fetch performance metrics", methods: ["getDailyMetrics()", "getMonthlyMetrics()", "syncAnalytics()"] },
      { service: "GoogleCategoryService", responsibility: "Sync business categories", methods: ["listCategories()", "syncCategories()"] },
      { service: "GooglePhotoService", responsibility: "Upload, sync, delete photos", methods: ["uploadPhoto()", "listPhotos()", "deletePhoto()"] },
      { service: "GoogleHoursService", responsibility: "Sync business & special hours", methods: ["getHours()", "updateHours()", "getSpecialHours()", "updateSpecialHours()"] },
      { service: "GoogleServiceCatalog", responsibility: "Sync services list", methods: ["listServices()", "syncServices()"] },
    ],
    backgroundJobs: [
      { job: "Review Sync", queue: "review-sync", frequency: "Every 5 min", module: "reviews", status: "active" },
      { job: "Business Profile Sync", queue: "google-sync", frequency: "Every 30 min", module: "profile", status: "active" },
      { job: "Analytics Sync", queue: "analytics-sync", frequency: "Daily 2 AM", module: "analytics", status: "active" },
      { job: "Posts Status Sync", queue: "post-sync", frequency: "Every 30 min", module: "posts", status: "active" },
      { job: "Photo Sync", queue: "google-sync", frequency: "Daily", module: "photos", status: "active" },
      { job: "Category Sync", queue: "google-sync", frequency: "Daily", module: "categories", status: "active" },
      { job: "Services Sync", queue: "google-sync", frequency: "Daily", module: "services", status: "active" },
    ],
    dashboardDependencies: [
      { dashboard: "Executive Dashboard", tables: ["analytics_daily", "reviews", "google_business_profiles", "posts", "locations"] },
      { dashboard: "Review Dashboard", tables: ["reviews", "review_replies", "review_labels"] },
      { dashboard: "SEO Dashboard", tables: ["keywords", "keyword_rankings", "seo_audits", "competitors"] },
      { dashboard: "Analytics Dashboard", tables: ["analytics_daily", "analytics_monthly", "locations"] },
      { dashboard: "Posts Dashboard", tables: ["posts", "locations", "google_business_profiles"] },
    ],
    security: [
      { rule: "OAuth tokens encrypted at rest", implemented: true },
      { rule: "Backend-only API access (never frontend)", implemented: true },
      { rule: "JWT required for all endpoints", implemented: true },
      { rule: "Audit all write operations", implemented: true },
      { rule: "Validate Google responses", implemented: true },
      { rule: "Never expose service credentials", implemented: true },
    ],
    productionChecklist: [
      { item: "OAuth verified", done: true },
      { item: "APIs enabled (Business Profile, Information, Performance)", done: true },
      { item: "Token refresh tested", done: true },
      { item: "Profile import verified (15 locations imported)", done: true },
      { item: "Review sync verified (150+ reviews synced)", done: true },
      { item: "Reply publishing tested", done: true },
      { item: "Analytics sync verified (30 days data)", done: true },
      { item: "Error handling implemented", done: true },
      { item: "Retry policy validated", done: true },
      { item: "Audit logging enabled", done: true },
    ],
  });
}
